[package]
name = "bench_diff"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Reliably compare the latencies of two functions/closures."
repository = "https://github.com/pvillela/rust-bench-diff/tree/main"
documentation = "https://docs.rs/bench_diff/latest/bench_diff/"
readme = "README.md"
keywords = [
    "latency",
    "measurement",
    "performance",
    "benchmarking",
    "difference",
]
categories = ["development-tools::profiling"]
exclude = ["CHANGELOG.md", "*.sh", ".gitignore"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdrhistogram = "7.5"
statrs = "0.18"
sha2 = { version = "0.10", optional = true }

[dev-dependencies]
hypors = "0.2"
polars = "0.43"                                      # required by hypors
rand = { version = "0.9.0", features = ["std_rng"] }
rand_distr = "0.5"

[features]
# utilities for creation of synthetic benchmarks
dev_utils = ["dep:sha2"]

# intended only to be used in development
# dev = []

[[bench]]
name = "bench_nanos"
harness = false

[[bench]]
name = "bench_micros"
harness = false

[[bench]]
name = "bench_micros_in_nanos"
harness = false

[[bench]]
name = "bench_millis"
harness = false

[[bench]]
name = "bench_millis_in_micros"
harness = false
